server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aibishe?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 2843586907x
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.newDemo.bean